"""
Execution node — runs solution code against both test suites in the sandbox.

Dual-oracle strategy (Fix 5):
  - Spec tests: generated from the task description alone, before any code
    exists. They test correctness against the specification.
  - Adversarial tests: generated by the QA agent after seeing the code.
    They hunt for edge cases in the specific implementation.

Both suites must pass for the execution to be considered successful.
Failure summaries clearly label which suite caught the failure so the
debugger can distinguish spec violations from implementation edge cases.

This is the only node that executes code. All execution is delegated to
the sandbox module which runs everything in a separate subprocess.
"""

import logging
from typing import Any

from agent.state import AgentState, IterationRecord
from agent.events import step_event, failure_event, success_event
from sandbox.python_executor import execute, format_failure_summary

logger = logging.getLogger(__name__)


async def execute_solution(state: AgentState) -> dict[str, Any]:
    """LangGraph node: execute solution against both spec and adversarial tests."""
    iteration = state.get("iteration", 0)
    events = list(state.get("events", []))
    current_code = state["current_code"]

    spec_test_code = state.get("spec_test_code", "")
    adversarial_test_code = state.get("current_test_code", "")

    # --- Run spec tests (generated blind from specification) ---
    spec_passed = True
    spec_summary = ""
    if spec_test_code.strip():
        events.append(step_event(
            "Running spec-blind oracle tests...",
            iteration=iteration,
        ).to_dict())
        spec_result = await execute(
            solution_code=current_code,
            test_code=spec_test_code,
        )
        spec_passed = spec_result.passed
        if not spec_passed:
            spec_summary = "SPEC TEST FAILURES:\n" + format_failure_summary(spec_result)
        logger.info(
            "Spec tests: passed=%s elapsed=%.2fs (iteration=%d)",
            spec_result.passed, spec_result.elapsed_seconds, iteration,
        )

    # --- Run adversarial tests (generated by QA agent after seeing code) ---
    events.append(step_event(
        "Running adversarial tests...",
        iteration=iteration,
    ).to_dict())
    adv_result = await execute(
        solution_code=current_code,
        test_code=adversarial_test_code,
    )
    adv_passed = adv_result.passed
    adv_summary = ""
    if not adv_passed:
        adv_summary = "ADVERSARIAL TEST FAILURES:\n" + format_failure_summary(adv_result)
    logger.info(
        "Adversarial tests: passed=%s elapsed=%.2fs (iteration=%d)",
        adv_result.passed, adv_result.elapsed_seconds, iteration,
    )

    # --- Combine outcomes ---
    overall_passed = spec_passed and adv_passed

    failure_parts = [p for p in [spec_summary, adv_summary] if p]
    combined_failure_summary = "\n\n".join(failure_parts) if failure_parts else ""
    if overall_passed:
        combined_failure_summary = ""

    if overall_passed:
        events.append(success_event(code=current_code, iteration=iteration).to_dict())
        new_status = "success"
    else:
        events.append(failure_event(
            summary=combined_failure_summary,
            iteration=iteration,
            failed_assertions=(
                (adv_result.failed_assertions if not adv_passed else [])
            ),
        ).to_dict())
        new_status = "running"

    # Record this iteration for the debugger's history context
    iteration_record: IterationRecord = {
        "iteration": iteration,
        "code": current_code,
        "test_code": adversarial_test_code,
        "passed": overall_passed,
        "failure_summary": combined_failure_summary,
        "root_cause": state.get("root_cause", ""),
        "failure_category": state.get("failure_category", ""),
        "repair_strategy": state.get("repair_strategy", ""),
    }
    history = list(state.get("iteration_history", []))
    history.append(iteration_record)

    return {
        "last_execution_passed": overall_passed,
        "last_failure_summary": combined_failure_summary,
        "iteration_history": history,
        "status": new_status,
        "events": events,
    }
